name: court-checker

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * 5"  # 毎週金曜 09:00（CEST）。冬は 0 8 * * 5 に

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      HEADLESS: "true"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run checker (print to console & file)
        shell: bash
        run: |
          set -euo pipefail
          python -u check_next2weeks_targets.py | tee result.txt
          echo "---- result.txt (below) ----"
          cat result.txt || true

      - name: Upload artifacts (result, csv, screenshots)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: run-artifacts
          path: |
            result.txt
            results.csv
            screenshots/**
          if-no-files-found: ignore
